addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"       % "0.4.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"       % "0.9.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"       % "0.10.4")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"        % "0.6.3")
addSbtPlugin("org.typelevel"             % "sbt-typelevel"      % "0.4.17")
addSbtPlugin("org.typelevel"             % "sbt-typelevel-site" % "0.4.17")
